<h1 class="subTitle"><i class="fa fa-user"></i>Vous connectez</h1>

<form class="generic-form" action="" method="POST">

    <div class="form-group row">
        <label for="example-email-input" class="col-2 col-form-label">Email</label>
        <div class="col-10">
            <input class="form-control" name="email" type="email" value="<?= (!empty($email) ? htmlspecialchars($email) : '') ?>" id="example-email-input">
        </div>
    </div>


    <div class="form-group">
        <label for="password" class="col-2 col-form-label">Password</label>
        <div class="col-10">
            <input class="form-control" name="password" type="Password" value="" id="password">
        </div>
    </div>
    <article class="central">
        <input class="btn btn-primary" type="submit" value="Connexion">
        <a class="btn btn-secondary " href="/index.php">Annuler</a>
    </article>
</form>    